name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  unit-tests:
    uses: ./.github/workflows/test.unit.yml
    secrets: inherit

  e2e-tests:
    uses: ./.github/workflows/test.e2e.yml
    needs: unit-tests
    secrets: inherit
