name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  call-tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deploy:
    needs: call-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          set -e
          cd /home/debian

          # Cloner le projet si le dossier n'existe pas
          if [ ! -d "eventhub" ]; then
            git clone git@github.com:rachidje/eventhub.git eventhub
          fi

          cd eventhub

          # Vérifie que c'est bien un dépôt Git
          if [ ! -d ".git" ]; then
            echo "Erreur : ce n'est pas un dépôt Git."
            exit 1
          fi

          git pull origin main

          docker compose down
          docker compose build --no-cache || {
            echo "Le build a échoué, arrêt du déploiement."
            exit 1
          }
          docker compose up -d

