name: Unit Tests

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./back
        run: npm ci

      - name: Run unit tests
        working-directory: ./back
        run: npm run test:unit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./back/coverage/cobertura-coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
