name: End-to-End Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./back
        run: npm ci

      - name: Ensure Docker is ready (for Testcontainers)
        run: |
          docker info
          docker ps

      - name: Run E2E tests (Testcontainers)
        working-directory: ./back
        run: npm run test:e2e
